ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY wsl/prepare-wsl-rootfs.sh /usr/local/bin/prepare-wsl-rootfs.sh

RUN chmod 0755 /usr/local/bin/prepare-wsl-rootfs.sh && \
    /usr/local/bin/prepare-wsl-rootfs.sh && \
    rm -f /usr/local/bin/prepare-wsl-rootfs.sh
